### ISSUE TITLE
Replacing a group of tokens

### ISSUE THREAD

**Issue by tomkcook** [aroberge/token-utils#6]
What is the right way to replace a group of tokens with a different set of tokens?  It feels like I must be missing something.  There doesn't seem to be an easy way of constructing a list of new tokens and some of the obvious ways of doing this produce odd results.  For instance this transform:

```
def transform_source(source, **_):
    tokens = token_utils.tokenize(source)
    for ii in range(2, 4):
        del tokens[ii]

    tokens.insert(2, '"Some Text"')
    return token_utils.untokenize(tokens)
```

on this source:

```
x = Some Text
```

produces this transformed source:

```
x ="Some Text" Some Text
```

What is the right way to do this?  Is there a reliable way?

**Comment by aroberge** [comment]
Rather than deleting a given token, try to set its string attribute to an empty string. Something like:
```
def transform_source(source, **_):
    tokens = token_utils.tokenize(source)
    for ii in range(2, 4):
        tokens[ii].string = ""
    tokens.insert(2, '"Some text"')
    return token_utils.untokenize(tokens)
```
will probably do what you want.

**Comment by aroberge** [comment]
Quick example:
```
> python
Python 3.10.8 (tags/v3.10.8:aaaf517, Oct 11 2022, 16:50:30) [MSC v.1933 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import token_utils as tu
>>> tokens = tu.tokenize("x = Some Text")
>>> for i in range(2, 4):
...     tokens[i] = ""
...
>>> tokens.insert(2, '"New string"')
>>> tu.untokenize(tokens)
'x ="New string"'
```

**Comment by tomkcook** [comment]
Thanks for getting back to me.  I think this worked, but was quite error-prone; in the end, I have abandoned the attempt to edit the tokenized list of tokens and constructed a new list instead.
